name: Deploy Migration CI/CD

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Authentictate to GCP
        # This creates a temporary file from your secret for Terraform to use
        run: |
          echo "$GCP_JSON_KEY" > provider_key.json
        env:
          GCP_JSON_KEY: ${{ secrets.GCP_SA_KEY }}
      - name: Create GCP Service Account Key File
        run: echo '${{ secrets.GCP_SA_KEY }}' > gcp_credentials.json

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json # Added ./ to be explicit
          

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_LOG: DEBUG  # Optional: Enable detailed logging for troubleshooting
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json
          TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }} # <--- Add this
          TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST }}   # <--- Good practice to add this too

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json
          TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }} # <--- Add this
          TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST }}   # <--- Good practice to add this too

  #i. validation Stage
  validate:
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nativo_migration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: databricks/setup-cli@main
        with:
          version: "0.220.0"  #
      - name: databricks bundle valdiate
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  
  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nativo_migration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # ADD THE SAME UV INSTALL STEPS HERE
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Add uv to PATH
        run: echo "$HOME/.astral-uv/bin" >> $GITHUB_PATH
      
      - name: databricks CLI setup
        uses: databricks/setup-cli@main
      
      - name: deploy to dev
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
